### ISSUE TITLE
[Bug] IssueInfoView에서 마크다운 잘리는 현상

### ISSUE THREAD

**Issue by JH713** [goorung/Gitodo#66]
### 🔍 버그 상황
 
- 마크다운이 길 때 뒷 부분이 잘리는 경우가 있음

### 🙋🏻‍♀️ 해결 제안

- MarkdownView의 문제인지 layout 문제 확인 후 해결 예정

**Comment by noeyiz** [comment]
앗 ! 레이아웃 수정하는 김에 이렇게 한 줄만 있을 때 위에 딱 붙어서 ... 위에 살짝 간격 줄 수 있나유

<img width="250" src="https://github.com/goorung/Gitodo/assets/116897060/1b28fc7a-b6b3-4d5f-86a6-52711f93c7d9">
